server:
  port: 8000
spring:
  application:
    name: microservice-provider-user

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://enreka1:8000/eureka/
  instance:
    preferIpAddress: true